# Generated by Django 3.2.6 on 2021-09-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
